
# This is your Supabase project configuration

project_id = "zzbzcfrklspkhrfgkmcw"

# Set these when deploying to production
site_url = "https://zzbzcfrklspkhrfgkmcw.supabase.co"
api.url = "https://zzbzcfrklspkhrfgkmcw.supabase.co"

